// JOIN ALL ELEMENTS OF THE FOLLOWING ARRAY INTO A STRING:

const join = [Red, Green, White, Black];
console.log(join.toString());

// Write a function to check if a string contains only digits.

// const onlyDigits = ["183646"];

// if (onlyDigits >= 0) {
//   console.log("true");
// }

const onlyDigits1 = ["183646"];
if (onlyDigits >= 0) {
  console.log("true");
} else {
  console.log("false");
}

// Write a function to check if the input is not ending with word 'cat'.

const notEnding = ["hello world"];

if (notEnding.endsWith("cat")) {
  console.log("false");
} else {
  console.log("true");
}
